---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-shared-pv
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: shared-pv
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: minio
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.2.9
    helm:
      values: |
        mode: "standalone"
        persistence:
          existingClaim: shared-pvc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
